version: '3.8'

services:
  postgres_certification_project:
    container_name: postgres_certification_project
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pg_nlw
